---
title: "Test Zone"
output: github_document
date: "2022-11-20"
author: Mrozinski Alexandre
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo=TRUE, eval=TRUE)
```

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo=TRUE, eval=TRUE)

samples.out <- rownames(seqtab.nochim)
subject <- sapply(strsplit(samples.out, "D"), `[`, 1)

fond <- sapply(strsplit(samples.out, "_"), `[`, 2)

surface <- substr(seqtab.nochim,1,9999) 
median <- substr(seqtab.nochim,1,9999)
#fond <- substr(seqtab.nochim,1,9999)

#fond <- as.integer(sapply(strsplit(samples.out, "Fond"), `[`, 1))


tableau <- data.frame(Station = subject, Surface = surface, Median = median, Fond = fond)

#tableau$Station <- c("median", "median", "fond")
#dataframe
print(tableau)
```

```{r}
samples.out <- rownames(seqtab.nochim)
station <- sapply(strsplit(samples.out, "_"), `[`, 2)


fond <- as.integer(sapply(strsplit(samples.out, "_"), `[`, 2))
median <- as.integer(sapply(strsplit(samples.out, "_"), `[`, 2))
surface <- as.integer(sapply(strsplit(samples.out, "_"), `[`, 2))

tableau <- data.frame(Station=station, Surface=surface, Median=median, Fond=fond)

tableau$When <- "Early"
tableau$When[tableau$Station>999999] <- "Late"

rownames(tableau) <- samples.out
print(tableau)
```

```{r}
ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_data(tableau), 
               tax_table(taxa))
ps <- prune_samples(sample_names(ps), ps) 
```

```{r}
dna <- Biostrings::DNAStringSet(taxa_names(ps))
names(dna) <- taxa_names(ps)
ps <- merge_phyloseq(ps, dna)
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps)))
ps
```
```{r}
plot_richness(ps, x="Station", measures=c("Shannon", "Simpson"), color="When")
```

```{r}
# Transform data to proportions as appropriate for Bray-Curtis distances
ps.prop <- transform_sample_counts(ps, function(otu) otu/sum(otu))
ord.nmds.bray <- ordinate(ps.prop, method="NMDS", distance="bray")
```

```{r}
plot_ordination(ps.prop, ord.nmds.bray, color="Where", title="Bray NMDS")
```

```{r}
top20 <- names(sort(taxa_sums(ps), decreasing=TRUE))[1:20]
ps.top20 <- transform_sample_counts(ps, function(OTU) OTU/sum(OTU))
ps.top20 <- prune_taxa(top20, ps.top20)
plot_bar(ps.top20, x="Station", fill="Family") + facet_wrap(~When, scales="free_x")
```



